-- S6f: categorie modificabili dall'admin. Fonte di verità = questa tabella; place-types.it.json resta solo come dato iniziale.
-- gruppo_ordine: posizione del gruppo (non modificabile dall'app); ordine: posizione nel gruppo; parole: sinonimi (array JSON).
CREATE TABLE categorie (
  type TEXT PRIMARY KEY,
  label TEXT NOT NULL CHECK (length(trim(label)) > 0),
  gruppo TEXT NOT NULL,
  gruppo_ordine INTEGER NOT NULL,
  generico INTEGER NOT NULL DEFAULT 0 CHECK (generico IN (0, 1)),
  parole TEXT NOT NULL DEFAULT '[]',
  ordine INTEGER NOT NULL
);

INSERT INTO categorie (type, label, gruppo, gruppo_ordine, generico, parole, ordine) VALUES
  ('parking_lot', 'Area di parcheggio', 'Auto e mezzi', 1, 0, '[]', 1),
  ('rest_stop', 'Area di sosta', 'Auto e mezzi', 1, 0, '[]', 2),
  ('car_wash', 'Autolavaggio', 'Auto e mezzi', 1, 0, '[]', 3),
  ('car_rental', 'Autonoleggio', 'Auto e mezzi', 1, 0, '[]', 4),
  ('parking_garage', 'Autorimessa', 'Auto e mezzi', 1, 0, '[]', 5),
  ('electric_vehicle_charging_station', 'Colonnina di ricarica elettrica', 'Auto e mezzi', 1, 0, '[]', 6),
  ('car_dealer', 'Concessionario auto', 'Auto e mezzi', 1, 0, '[]', 7),
  ('truck_dealer', 'Concessionario camion', 'Auto e mezzi', 1, 0, '[]', 8),
  ('gas_station', 'Distributore di carburante', 'Auto e mezzi', 1, 0, '["benzinaio","distributore"]', 9),
  ('tire_shop', 'Gommista', 'Auto e mezzi', 1, 0, '["gommista","pneumatici"]', 10),
  ('car_repair', 'Officina meccanica', 'Auto e mezzi', 1, 0, '["meccanico","officina"]', 11),
  ('parking', 'Parcheggio', 'Auto e mezzi', 1, 0, '[]', 12),
  ('ebike_charging_station', 'Ricarica e-bike', 'Auto e mezzi', 1, 0, '[]', 13),
  ('farm', 'Azienda agricola', 'Attività e aziende', 2, 0, '[]', 1),
  ('manufacturer', 'Azienda manifatturiera', 'Attività e aziende', 2, 0, '[]', 2),
  ('business_center', 'Centro servizi per aziende', 'Attività e aziende', 2, 0, '[]', 3),
  ('supplier', 'Fornitore', 'Attività e aziende', 2, 0, '[]', 4),
  ('ranch', 'Ranch', 'Attività e aziende', 2, 0, '[]', 5),
  ('corporate_office', 'Sede aziendale', 'Attività e aziende', 2, 0, '[]', 6),
  ('coworking_space', 'Spazio di coworking', 'Attività e aziende', 2, 0, '[]', 7),
  ('television_studio', 'Studio televisivo', 'Attività e aziende', 2, 0, '[]', 8),
  ('auditorium', 'Auditorium', 'Cultura', 3, 0, '[]', 1),
  ('castle', 'Castello', 'Cultura', 3, 0, '[]', 2),
  ('fountain', 'Fontana', 'Cultura', 3, 0, '[]', 3),
  ('art_gallery', 'Galleria d''arte', 'Cultura', 3, 0, '[]', 4),
  ('cultural_landmark', 'Luogo di interesse culturale', 'Cultura', 3, 0, '[]', 5),
  ('historical_place', 'Luogo storico', 'Cultura', 3, 0, '[]', 6),
  ('monument', 'Monumento', 'Cultura', 3, 0, '[]', 7),
  ('museum', 'Museo', 'Cultura', 3, 0, '[]', 8),
  ('art_museum', 'Museo d''arte', 'Cultura', 3, 0, '[]', 9),
  ('history_museum', 'Museo di storia', 'Cultura', 3, 0, '[]', 10),
  ('sculpture', 'Scultura', 'Cultura', 3, 0, '[]', 11),
  ('art_studio', 'Studio d''artista', 'Cultura', 3, 0, '[]', 12),
  ('performing_arts_theater', 'Teatro', 'Cultura', 3, 0, '[]', 13),
  ('educational_institution', 'Istituto di istruzione', 'Istruzione', 4, 1, '[]', 1),
  ('library', 'Biblioteca', 'Istruzione', 4, 0, '[]', 2),
  ('academic_department', 'Dipartimento universitario', 'Istruzione', 4, 0, '[]', 3),
  ('research_institute', 'Istituto di ricerca', 'Istruzione', 4, 0, '[]', 4),
  ('school', 'Scuola', 'Istruzione', 4, 0, '[]', 5),
  ('preschool', 'Scuola dell''infanzia', 'Istruzione', 4, 0, '[]', 6),
  ('primary_school', 'Scuola primaria', 'Istruzione', 4, 0, '[]', 7),
  ('secondary_school', 'Scuola secondaria', 'Istruzione', 4, 0, '[]', 8),
  ('university', 'Università', 'Istruzione', 4, 0, '[]', 9),
  ('aquarium', 'Acquario', 'Intrattenimento e svago', 5, 0, '[]', 1),
  ('amphitheatre', 'Anfiteatro', 'Intrattenimento e svago', 5, 0, '[]', 2),
  ('barbecue_area', 'Area barbecue', 'Intrattenimento e svago', 5, 0, '[]', 3),
  ('dog_park', 'Area cani', 'Intrattenimento e svago', 5, 0, '[]', 4),
  ('hiking_area', 'Area escursionistica', 'Intrattenimento e svago', 5, 0, '[]', 5),
  ('off_roading_area', 'Area fuoristrada', 'Intrattenimento e svago', 5, 0, '[]', 6),
  ('picnic_ground', 'Area picnic', 'Intrattenimento e svago', 5, 0, '[]', 7),
  ('tourist_attraction', 'Attrazione turistica', 'Intrattenimento e svago', 5, 0, '[]', 8),
  ('bowling_alley', 'Bowling', 'Intrattenimento e svago', 5, 0, '[]', 9),
  ('childrens_camp', 'Campo per bambini', 'Intrattenimento e svago', 5, 0, '[]', 10),
  ('casino', 'Casinò', 'Intrattenimento e svago', 5, 0, '[]', 11),
  ('community_center', 'Centro comunitario', 'Intrattenimento e svago', 5, 0, '[]', 12),
  ('convention_center', 'Centro congressi', 'Intrattenimento e svago', 5, 0, '[]', 13),
  ('cultural_center', 'Centro culturale', 'Intrattenimento e svago', 5, 0, '[]', 14),
  ('paintball_center', 'Centro paintball', 'Intrattenimento e svago', 5, 0, '[]', 15),
  ('adventure_sports_center', 'Centro sport d''avventura', 'Intrattenimento e svago', 5, 0, '[]', 16),
  ('visitor_center', 'Centro visitatori', 'Intrattenimento e svago', 5, 0, '[]', 17),
  ('movie_theater', 'Cinema', 'Intrattenimento e svago', 5, 0, '[]', 18),
  ('night_club', 'Discoteca', 'Intrattenimento e svago', 5, 0, '[]', 19),
  ('garden', 'Giardino', 'Intrattenimento e svago', 5, 0, '[]', 20),
  ('internet_cafe', 'Internet point', 'Intrattenimento e svago', 5, 0, '[]', 21),
  ('karaoke', 'Karaoke', 'Intrattenimento e svago', 5, 0, '[]', 22),
  ('live_music_venue', 'Locale con musica dal vivo', 'Intrattenimento e svago', 5, 0, '[]', 23),
  ('comedy_club', 'Locale di cabaret', 'Intrattenimento e svago', 5, 0, '[]', 24),
  ('event_venue', 'Location per eventi', 'Intrattenimento e svago', 5, 0, '[]', 25),
  ('wedding_venue', 'Location per matrimoni', 'Intrattenimento e svago', 5, 0, '[]', 26),
  ('miniature_golf_course', 'Minigolf', 'Intrattenimento e svago', 5, 0, '[]', 27),
  ('roller_coaster', 'Montagne russe', 'Intrattenimento e svago', 5, 0, '[]', 28),
  ('historical_landmark', 'Monumento storico', 'Intrattenimento e svago', 5, 0, '[]', 29),
  ('movie_rental', 'Noleggio film', 'Intrattenimento e svago', 5, 0, '[]', 30),
  ('botanical_garden', 'Orto botanico', 'Intrattenimento e svago', 5, 0, '[]', 31),
  ('park', 'Parco', 'Intrattenimento e svago', 5, 0, '[]', 32),
  ('water_park', 'Parco acquatico', 'Intrattenimento e svago', 5, 0, '[]', 33),
  ('city_park', 'Parco cittadino', 'Intrattenimento e svago', 5, 0, '[]', 34),
  ('amusement_park', 'Parco divertimenti', 'Intrattenimento e svago', 5, 0, '[]', 35),
  ('wildlife_park', 'Parco faunistico', 'Intrattenimento e svago', 5, 0, '[]', 36),
  ('indoor_playground', 'Parco giochi al coperto', 'Intrattenimento e svago', 5, 0, '[]', 37),
  ('national_park', 'Parco nazionale', 'Intrattenimento e svago', 5, 0, '[]', 38),
  ('cycling_park', 'Parco per ciclismo', 'Intrattenimento e svago', 5, 0, '[]', 39),
  ('state_park', 'Parco regionale', 'Intrattenimento e svago', 5, 0, '[]', 40),
  ('plaza', 'Piazza', 'Intrattenimento e svago', 5, 0, '[]', 41),
  ('go_karting_venue', 'Pista di kart', 'Intrattenimento e svago', 5, 0, '[]', 42),
  ('planetarium', 'Planetario', 'Intrattenimento e svago', 5, 0, '[]', 43),
  ('marina', 'Porto turistico', 'Intrattenimento e svago', 5, 0, '[]', 44),
  ('wildlife_refuge', 'Riserva faunistica', 'Intrattenimento e svago', 5, 0, '[]', 45),
  ('ferris_wheel', 'Ruota panoramica', 'Intrattenimento e svago', 5, 0, '[]', 46),
  ('banquet_hall', 'Sala banchetti', 'Intrattenimento e svago', 5, 0, '[]', 47),
  ('concert_hall', 'Sala concerti', 'Intrattenimento e svago', 5, 0, '[]', 48),
  ('dance_hall', 'Sala da ballo', 'Intrattenimento e svago', 5, 0, '[]', 49),
  ('philharmonic_hall', 'Sala filarmonica', 'Intrattenimento e svago', 5, 0, '[]', 50),
  ('amusement_center', 'Sala giochi', 'Intrattenimento e svago', 5, 0, '[]', 51),
  ('video_arcade', 'Sala videogiochi', 'Intrattenimento e svago', 5, 0, '[]', 52),
  ('skateboard_park', 'Skate park', 'Intrattenimento e svago', 5, 0, '[]', 53),
  ('opera_house', 'Teatro dell''opera', 'Intrattenimento e svago', 5, 0, '[]', 54),
  ('observation_deck', 'Terrazza panoramica', 'Intrattenimento e svago', 5, 0, '[]', 55),
  ('vineyard', 'Vigneto', 'Intrattenimento e svago', 5, 0, '[]', 56),
  ('zoo', 'Zoo', 'Intrattenimento e svago', 5, 0, '[]', 57),
  ('public_bath', 'Bagni pubblici', 'Strutture pubbliche', 6, 0, '[]', 1),
  ('public_bathroom', 'Servizi igienici pubblici', 'Strutture pubbliche', 6, 0, '[]', 2),
  ('stable', 'Stalla', 'Strutture pubbliche', 6, 0, '[]', 3),
  ('bank', 'Banca', 'Finanza', 7, 0, '["banca"]', 1),
  ('atm', 'Bancomat', 'Finanza', 7, 0, '[]', 2),
  ('accounting', 'Commercialista', 'Finanza', 7, 0, '["commercialista","ragioniere"]', 3),
  ('restaurant', 'Ristorante', 'Cibo e bevande', 8, 1, '[]', 1),
  ('food_court', 'Area ristoro (food court)', 'Cibo e bevande', 8, 0, '[]', 2),
  ('bagel_shop', 'Bagel shop', 'Cibo e bevande', 8, 0, '[]', 3),
  ('cafe', 'Bar / caffetteria', 'Cibo e bevande', 8, 0, '[]', 4),
  ('bar', 'Bar / pub (locale serale)', 'Cibo e bevande', 8, 0, '[]', 5),
  ('acai_shop', 'Bar di açaí', 'Cibo e bevande', 8, 0, '[]', 6),
  ('juice_shop', 'Bar di succhi e centrifugati', 'Cibo e bevande', 8, 0, '[]', 7),
  ('bar_and_grill', 'Bar e grill', 'Cibo e bevande', 8, 0, '[]', 8),
  ('beer_garden', 'Birreria all''aperto', 'Cibo e bevande', 8, 0, '[]', 9),
  ('brewery', 'Birrificio', 'Cibo e bevande', 8, 0, '[]', 10),
  ('bistro', 'Bistrot', 'Cibo e bevande', 8, 0, '[]', 11),
  ('brewpub', 'Brewpub', 'Cibo e bevande', 8, 0, '[]', 12),
  ('cat_cafe', 'Caffè dei gatti', 'Cibo e bevande', 8, 0, '[]', 13),
  ('dog_cafe', 'Caffè per cani', 'Cibo e bevande', 8, 0, '[]', 14),
  ('coffee_shop', 'Caffetteria (coffee shop)', 'Cibo e bevande', 8, 0, '[]', 15),
  ('winery', 'Cantina vinicola', 'Cibo e bevande', 8, 0, '[]', 16),
  ('coffee_stand', 'Chiosco del caffè', 'Cibo e bevande', 8, 0, '[]', 17),
  ('hot_dog_stand', 'Chiosco di hot dog', 'Cibo e bevande', 8, 0, '[]', 18),
  ('chocolate_shop', 'Cioccolateria', 'Cibo e bevande', 8, 0, '[]', 19),
  ('confectionery', 'Confetteria', 'Cibo e bevande', 8, 0, '[]', 20),
  ('meal_delivery', 'Consegna pasti a domicilio', 'Cibo e bevande', 8, 0, '[]', 21),
  ('diner', 'Diner', 'Cibo e bevande', 8, 0, '[]', 22),
  ('wine_bar', 'Enoteca con mescita', 'Cibo e bevande', 8, 0, '[]', 23),
  ('chocolate_factory', 'Fabbrica di cioccolato', 'Cibo e bevande', 8, 0, '[]', 24),
  ('fast_food_restaurant', 'Fast food', 'Cibo e bevande', 8, 0, '[]', 25),
  ('fish_and_chips_restaurant', 'Fish and chips', 'Cibo e bevande', 8, 0, '[]', 26),
  ('deli', 'Gastronomia', 'Cibo e bevande', 8, 0, '[]', 27),
  ('gastropub', 'Gastropub', 'Cibo e bevande', 8, 0, '[]', 28),
  ('ice_cream_shop', 'Gelateria', 'Cibo e bevande', 8, 0, '["gelateria"]', 29),
  ('hamburger_restaurant', 'Hamburgeria', 'Cibo e bevande', 8, 0, '[]', 30),
  ('salad_shop', 'Insalateria', 'Cibo e bevande', 8, 0, '[]', 31),
  ('japanese_izakaya_restaurant', 'Izakaya giapponese', 'Cibo e bevande', 8, 0, '[]', 32),
  ('kebab_shop', 'Kebab', 'Cibo e bevande', 8, 0, '[]', 33),
  ('dessert_restaurant', 'Locale di dolci', 'Cibo e bevande', 8, 0, '[]', 34),
  ('hot_dog_restaurant', 'Locale di hot dog', 'Cibo e bevande', 8, 0, '[]', 35),
  ('noodle_shop', 'Locale di noodle', 'Cibo e bevande', 8, 0, '[]', 36),
  ('soup_restaurant', 'Locale di zuppe', 'Cibo e bevande', 8, 0, '[]', 37),
  ('hookah_bar', 'Locale narghilè', 'Cibo e bevande', 8, 0, '[]', 38),
  ('brunch_restaurant', 'Locale per brunch', 'Cibo e bevande', 8, 0, '[]', 39),
  ('breakfast_restaurant', 'Locale per colazioni', 'Cibo e bevande', 8, 0, '[]', 40),
  ('lounge_bar', 'Lounge bar', 'Cibo e bevande', 8, 0, '[]', 41),
  ('cafeteria', 'Mensa', 'Cibo e bevande', 8, 0, '[]', 42),
  ('candy_store', 'Negozio di caramelle', 'Cibo e bevande', 8, 0, '[]', 43),
  ('donut_shop', 'Negozio di ciambelle', 'Cibo e bevande', 8, 0, '[]', 44),
  ('dessert_shop', 'Negozio di dolci', 'Cibo e bevande', 8, 0, '[]', 45),
  ('cake_shop', 'Negozio di torte', 'Cibo e bevande', 8, 0, '[]', 46),
  ('oyster_bar_restaurant', 'Ostricheria', 'Cibo e bevande', 8, 0, '[]', 47),
  ('bakery', 'Panificio', 'Cibo e bevande', 8, 0, '["panificio","panetteria","forno"]', 48),
  ('sandwich_shop', 'Paninoteca', 'Cibo e bevande', 8, 0, '[]', 49),
  ('meal_takeaway', 'Pasti da asporto', 'Cibo e bevande', 8, 0, '[]', 50),
  ('pastry_shop', 'Pasticceria', 'Cibo e bevande', 8, 0, '["pasticceria"]', 51),
  ('pizza_delivery', 'Pizza a domicilio', 'Cibo e bevande', 8, 0, '[]', 52),
  ('pizza_restaurant', 'Pizzeria', 'Cibo e bevande', 8, 0, '["pizzeria"]', 53),
  ('pub', 'Pub', 'Cibo e bevande', 8, 0, '[]', 54),
  ('irish_pub', 'Pub irlandese', 'Cibo e bevande', 8, 0, '[]', 55),
  ('buffet_restaurant', 'Ristorante a buffet', 'Cibo e bevande', 8, 0, '[]', 56),
  ('afghani_restaurant', 'Ristorante afghano', 'Cibo e bevande', 8, 0, '[]', 57),
  ('african_restaurant', 'Ristorante africano', 'Cibo e bevande', 8, 0, '[]', 58),
  ('american_restaurant', 'Ristorante americano', 'Cibo e bevande', 8, 0, '[]', 59),
  ('argentinian_restaurant', 'Ristorante argentino', 'Cibo e bevande', 8, 0, '[]', 60),
  ('asian_restaurant', 'Ristorante asiatico', 'Cibo e bevande', 8, 0, '[]', 61),
  ('australian_restaurant', 'Ristorante australiano', 'Cibo e bevande', 8, 0, '[]', 62),
  ('austrian_restaurant', 'Ristorante austriaco', 'Cibo e bevande', 8, 0, '[]', 63),
  ('barbecue_restaurant', 'Ristorante barbecue', 'Cibo e bevande', 8, 0, '[]', 64),
  ('korean_barbecue_restaurant', 'Ristorante barbecue coreano', 'Cibo e bevande', 8, 0, '[]', 65),
  ('mongolian_barbecue_restaurant', 'Ristorante barbecue mongolo', 'Cibo e bevande', 8, 0, '[]', 66),
  ('basque_restaurant', 'Ristorante basco', 'Cibo e bevande', 8, 0, '[]', 67),
  ('bavarian_restaurant', 'Ristorante bavarese', 'Cibo e bevande', 8, 0, '[]', 68),
  ('belgian_restaurant', 'Ristorante belga', 'Cibo e bevande', 8, 0, '[]', 69),
  ('bangladeshi_restaurant', 'Ristorante bengalese', 'Cibo e bevande', 8, 0, '[]', 70),
  ('burmese_restaurant', 'Ristorante birmano', 'Cibo e bevande', 8, 0, '[]', 71),
  ('brazilian_restaurant', 'Ristorante brasiliano', 'Cibo e bevande', 8, 0, '[]', 72),
  ('british_restaurant', 'Ristorante britannico', 'Cibo e bevande', 8, 0, '[]', 73),
  ('cajun_restaurant', 'Ristorante cajun', 'Cibo e bevande', 8, 0, '[]', 74),
  ('californian_restaurant', 'Ristorante californiano', 'Cibo e bevande', 8, 0, '[]', 75),
  ('cambodian_restaurant', 'Ristorante cambogiano', 'Cibo e bevande', 8, 0, '[]', 76),
  ('cantonese_restaurant', 'Ristorante cantonese', 'Cibo e bevande', 8, 0, '[]', 77),
  ('caribbean_restaurant', 'Ristorante caraibico', 'Cibo e bevande', 8, 0, '[]', 78),
  ('czech_restaurant', 'Ristorante ceco', 'Cibo e bevande', 8, 0, '[]', 79),
  ('chilean_restaurant', 'Ristorante cileno', 'Cibo e bevande', 8, 0, '[]', 80),
  ('chinese_restaurant', 'Ristorante cinese', 'Cibo e bevande', 8, 0, '[]', 81),
  ('colombian_restaurant', 'Ristorante colombiano', 'Cibo e bevande', 8, 0, '[]', 82),
  ('korean_restaurant', 'Ristorante coreano', 'Cibo e bevande', 8, 0, '[]', 83),
  ('croatian_restaurant', 'Ristorante croato', 'Cibo e bevande', 8, 0, '[]', 84),
  ('cuban_restaurant', 'Ristorante cubano', 'Cibo e bevande', 8, 0, '[]', 85),
  ('danish_restaurant', 'Ristorante danese', 'Cibo e bevande', 8, 0, '[]', 86),
  ('southwestern_us_restaurant', 'Ristorante del sud-ovest USA', 'Cibo e bevande', 8, 0, '[]', 87),
  ('eastern_european_restaurant', 'Ristorante dell''Europa orientale', 'Cibo e bevande', 8, 0, '[]', 88),
  ('chicken_wings_restaurant', 'Ristorante di alette di pollo', 'Cibo e bevande', 8, 0, '[]', 89),
  ('burrito_restaurant', 'Ristorante di burrito', 'Cibo e bevande', 8, 0, '[]', 90),
  ('japanese_curry_restaurant', 'Ristorante di curry giapponese', 'Cibo e bevande', 8, 0, '[]', 91),
  ('falafel_restaurant', 'Ristorante di falafel', 'Cibo e bevande', 8, 0, '[]', 92),
  ('fondue_restaurant', 'Ristorante di fonduta', 'Cibo e bevande', 8, 0, '[]', 93),
  ('gyro_restaurant', 'Ristorante di gyros', 'Cibo e bevande', 8, 0, '[]', 94),
  ('chinese_noodle_restaurant', 'Ristorante di noodle cinesi', 'Cibo e bevande', 8, 0, '[]', 95),
  ('seafood_restaurant', 'Ristorante di pesce', 'Cibo e bevande', 8, 0, '[]', 96),
  ('chicken_restaurant', 'Ristorante di pollo', 'Cibo e bevande', 8, 0, '[]', 97),
  ('ramen_restaurant', 'Ristorante di ramen', 'Cibo e bevande', 8, 0, '[]', 98),
  ('dumpling_restaurant', 'Ristorante di ravioli', 'Cibo e bevande', 8, 0, '[]', 99),
  ('shawarma_restaurant', 'Ristorante di shawarma', 'Cibo e bevande', 8, 0, '[]', 100),
  ('sushi_restaurant', 'Ristorante di sushi', 'Cibo e bevande', 8, 0, '[]', 101),
  ('taco_restaurant', 'Ristorante di tacos', 'Cibo e bevande', 8, 0, '[]', 102),
  ('tapas_restaurant', 'Ristorante di tapas', 'Cibo e bevande', 8, 0, '[]', 103),
  ('tonkatsu_restaurant', 'Ristorante di tonkatsu', 'Cibo e bevande', 8, 0, '[]', 104),
  ('dim_sum_restaurant', 'Ristorante dim sum', 'Cibo e bevande', 8, 0, '[]', 105),
  ('ethiopian_restaurant', 'Ristorante etiope', 'Cibo e bevande', 8, 0, '[]', 106),
  ('european_restaurant', 'Ristorante europeo', 'Cibo e bevande', 8, 0, '[]', 107),
  ('filipino_restaurant', 'Ristorante filippino', 'Cibo e bevande', 8, 0, '[]', 108),
  ('french_restaurant', 'Ristorante francese', 'Cibo e bevande', 8, 0, '[]', 109),
  ('fusion_restaurant', 'Ristorante fusion', 'Cibo e bevande', 8, 0, '[]', 110),
  ('asian_fusion_restaurant', 'Ristorante fusion asiatico', 'Cibo e bevande', 8, 0, '[]', 111),
  ('japanese_restaurant', 'Ristorante giapponese', 'Cibo e bevande', 8, 0, '[]', 112),
  ('fine_dining_restaurant', 'Ristorante gourmet', 'Cibo e bevande', 8, 0, '[]', 113),
  ('greek_restaurant', 'Ristorante greco', 'Cibo e bevande', 8, 0, '[]', 114),
  ('halal_restaurant', 'Ristorante halal', 'Cibo e bevande', 8, 0, '[]', 115),
  ('hawaiian_restaurant', 'Ristorante hawaiano', 'Cibo e bevande', 8, 0, '[]', 116),
  ('hot_pot_restaurant', 'Ristorante hot pot', 'Cibo e bevande', 8, 0, '[]', 117),
  ('indian_restaurant', 'Ristorante indiano', 'Cibo e bevande', 8, 0, '[]', 118),
  ('north_indian_restaurant', 'Ristorante indiano del nord', 'Cibo e bevande', 8, 0, '[]', 119),
  ('south_indian_restaurant', 'Ristorante indiano del sud', 'Cibo e bevande', 8, 0, '[]', 120),
  ('indonesian_restaurant', 'Ristorante indonesiano', 'Cibo e bevande', 8, 0, '[]', 121),
  ('irish_restaurant', 'Ristorante irlandese', 'Cibo e bevande', 8, 0, '[]', 122),
  ('israeli_restaurant', 'Ristorante israeliano', 'Cibo e bevande', 8, 0, '[]', 123),
  ('italian_restaurant', 'Ristorante italiano', 'Cibo e bevande', 8, 0, '[]', 124),
  ('latin_american_restaurant', 'Ristorante latinoamericano', 'Cibo e bevande', 8, 0, '[]', 125),
  ('lebanese_restaurant', 'Ristorante libanese', 'Cibo e bevande', 8, 0, '[]', 126),
  ('malaysian_restaurant', 'Ristorante malese', 'Cibo e bevande', 8, 0, '[]', 127),
  ('moroccan_restaurant', 'Ristorante marocchino', 'Cibo e bevande', 8, 0, '[]', 128),
  ('middle_eastern_restaurant', 'Ristorante mediorientale', 'Cibo e bevande', 8, 0, '[]', 129),
  ('mediterranean_restaurant', 'Ristorante mediterraneo', 'Cibo e bevande', 8, 0, '[]', 130),
  ('mexican_restaurant', 'Ristorante messicano', 'Cibo e bevande', 8, 0, '[]', 131),
  ('dutch_restaurant', 'Ristorante olandese', 'Cibo e bevande', 8, 0, '[]', 132),
  ('pakistani_restaurant', 'Ristorante pakistano', 'Cibo e bevande', 8, 0, '[]', 133),
  ('family_restaurant', 'Ristorante per famiglie', 'Cibo e bevande', 8, 0, '[]', 134),
  ('persian_restaurant', 'Ristorante persiano', 'Cibo e bevande', 8, 0, '[]', 135),
  ('peruvian_restaurant', 'Ristorante peruviano', 'Cibo e bevande', 8, 0, '[]', 136),
  ('polish_restaurant', 'Ristorante polacco', 'Cibo e bevande', 8, 0, '[]', 137),
  ('portuguese_restaurant', 'Ristorante portoghese', 'Cibo e bevande', 8, 0, '[]', 138),
  ('romanian_restaurant', 'Ristorante rumeno', 'Cibo e bevande', 8, 0, '[]', 139),
  ('russian_restaurant', 'Ristorante russo', 'Cibo e bevande', 8, 0, '[]', 140),
  ('scandinavian_restaurant', 'Ristorante scandinavo', 'Cibo e bevande', 8, 0, '[]', 141),
  ('sri_lankan_restaurant', 'Ristorante singalese', 'Cibo e bevande', 8, 0, '[]', 142),
  ('soul_food_restaurant', 'Ristorante soul food', 'Cibo e bevande', 8, 0, '[]', 143),
  ('spanish_restaurant', 'Ristorante spagnolo', 'Cibo e bevande', 8, 0, '[]', 144),
  ('south_american_restaurant', 'Ristorante sudamericano', 'Cibo e bevande', 8, 0, '[]', 145),
  ('swiss_restaurant', 'Ristorante svizzero', 'Cibo e bevande', 8, 0, '[]', 146),
  ('taiwanese_restaurant', 'Ristorante taiwanese', 'Cibo e bevande', 8, 0, '[]', 147),
  ('german_restaurant', 'Ristorante tedesco', 'Cibo e bevande', 8, 0, '[]', 148),
  ('tex_mex_restaurant', 'Ristorante tex-mex', 'Cibo e bevande', 8, 0, '[]', 149),
  ('thai_restaurant', 'Ristorante thailandese', 'Cibo e bevande', 8, 0, '[]', 150),
  ('tibetan_restaurant', 'Ristorante tibetano', 'Cibo e bevande', 8, 0, '[]', 151),
  ('turkish_restaurant', 'Ristorante turco', 'Cibo e bevande', 8, 0, '[]', 152),
  ('ukrainian_restaurant', 'Ristorante ucraino', 'Cibo e bevande', 8, 0, '[]', 153),
  ('hungarian_restaurant', 'Ristorante ungherese', 'Cibo e bevande', 8, 0, '[]', 154),
  ('vegan_restaurant', 'Ristorante vegano', 'Cibo e bevande', 8, 0, '[]', 155),
  ('vegetarian_restaurant', 'Ristorante vegetariano', 'Cibo e bevande', 8, 0, '[]', 156),
  ('vietnamese_restaurant', 'Ristorante vietnamita', 'Cibo e bevande', 8, 0, '[]', 157),
  ('western_restaurant', 'Ristorante western', 'Cibo e bevande', 8, 0, '[]', 158),
  ('yakiniku_restaurant', 'Ristorante yakiniku', 'Cibo e bevande', 8, 0, '[]', 159),
  ('yakitori_restaurant', 'Ristorante yakitori', 'Cibo e bevande', 8, 0, '[]', 160),
  ('tea_house', 'Sala da tè', 'Cibo e bevande', 8, 0, '[]', 161),
  ('snack_bar', 'Snack bar', 'Cibo e bevande', 8, 0, '[]', 162),
  ('sports_bar', 'Sports bar', 'Cibo e bevande', 8, 0, '[]', 163),
  ('steak_house', 'Steakhouse', 'Cibo e bevande', 8, 0, '[]', 164),
  ('coffee_roastery', 'Torrefazione', 'Cibo e bevande', 8, 0, '[]', 165),
  ('government_office', 'Ufficio governativo', 'Enti pubblici', 9, 1, '[]', 1),
  ('embassy', 'Ambasciata', 'Enti pubblici', 9, 0, '[]', 2),
  ('fire_station', 'Caserma dei vigili del fuoco', 'Enti pubblici', 9, 0, '[]', 3),
  ('neighborhood_police_station', 'Commissariato di quartiere', 'Enti pubblici', 9, 0, '[]', 4),
  ('city_hall', 'Municipio', 'Enti pubblici', 9, 0, '[]', 5),
  ('police', 'Polizia', 'Enti pubblici', 9, 0, '[]', 6),
  ('courthouse', 'Tribunale', 'Enti pubblici', 9, 0, '[]', 7),
  ('local_government_office', 'Ufficio comunale', 'Enti pubblici', 9, 0, '[]', 8),
  ('post_office', 'Ufficio postale', 'Enti pubblici', 9, 0, '["poste"]', 9),
  ('medical_clinic', 'Ambulatorio medico', 'Salute e benessere', 10, 0, '[]', 1),
  ('wellness_center', 'Centro benessere', 'Salute e benessere', 10, 0, '[]', 2),
  ('spa', 'Centro benessere (spa)', 'Salute e benessere', 10, 0, '[]', 3),
  ('skin_care_clinic', 'Centro dermatologico/estetico', 'Salute e benessere', 10, 0, '[]', 4),
  ('massage_spa', 'Centro massaggi e spa', 'Salute e benessere', 10, 0, '[]', 5),
  ('medical_center', 'Centro medico', 'Salute e benessere', 10, 0, '[]', 6),
  ('chiropractor', 'Chiropratico', 'Salute e benessere', 10, 0, '[]', 7),
  ('dental_clinic', 'Clinica odontoiatrica', 'Salute e benessere', 10, 0, '[]', 8),
  ('dentist', 'Dentista', 'Salute e benessere', 10, 0, '["dentista","odontoiatra"]', 9),
  ('pharmacy', 'Farmacia', 'Salute e benessere', 10, 0, '["farmacia"]', 10),
  ('physiotherapist', 'Fisioterapista', 'Salute e benessere', 10, 0, '[]', 11),
  ('medical_lab', 'Laboratorio analisi', 'Salute e benessere', 10, 0, '[]', 12),
  ('massage', 'Massaggi', 'Salute e benessere', 10, 0, '[]', 13),
  ('doctor', 'Medico', 'Salute e benessere', 10, 0, '["medico"]', 14),
  ('hospital', 'Ospedale', 'Salute e benessere', 10, 0, '[]', 15),
  ('general_hospital', 'Ospedale generale', 'Salute e benessere', 10, 0, '[]', 16),
  ('drugstore', 'Parafarmacia', 'Salute e benessere', 10, 0, '[]', 17),
  ('sauna', 'Sauna', 'Salute e benessere', 10, 0, '[]', 18),
  ('tanning_studio', 'Solarium', 'Salute e benessere', 10, 0, '[]', 19),
  ('yoga_studio', 'Studio di yoga', 'Salute e benessere', 10, 0, '[]', 20),
  ('condominium_complex', 'Complesso condominiale', 'Abitazioni', 11, 0, '[]', 1),
  ('apartment_complex', 'Complesso di appartamenti', 'Abitazioni', 11, 0, '[]', 2),
  ('housing_complex', 'Complesso residenziale', 'Abitazioni', 11, 0, '[]', 3),
  ('apartment_building', 'Condominio', 'Abitazioni', 11, 0, '[]', 4),
  ('lodging', 'Struttura ricettiva', 'Alloggi', 12, 1, '[]', 1),
  ('farmstay', 'Agriturismo', 'Alloggi', 12, 0, '[]', 2),
  ('hotel', 'Albergo', 'Alloggi', 12, 0, '[]', 3),
  ('rv_park', 'Area camper', 'Alloggi', 12, 0, '[]', 4),
  ('bed_and_breakfast', 'Bed and breakfast', 'Alloggi', 12, 0, '[]', 5),
  ('camping_cabin', 'Bungalow da campeggio', 'Alloggi', 12, 0, '[]', 6),
  ('private_guest_room', 'Camera privata per ospiti', 'Alloggi', 12, 0, '[]', 7),
  ('campground', 'Campeggio', 'Alloggi', 12, 0, '[]', 8),
  ('guest_house', 'Casa per ospiti', 'Alloggi', 12, 0, '[]', 9),
  ('cottage', 'Casa vacanze', 'Alloggi', 12, 0, '[]', 10),
  ('inn', 'Locanda', 'Alloggi', 12, 0, '[]', 11),
  ('japanese_inn', 'Locanda giapponese (ryokan)', 'Alloggi', 12, 0, '[]', 12),
  ('budget_japanese_inn', 'Locanda giapponese economica', 'Alloggi', 12, 0, '[]', 13),
  ('motel', 'Motel', 'Alloggi', 12, 0, '[]', 14),
  ('hostel', 'Ostello', 'Alloggi', 12, 0, '[]', 15),
  ('mobile_home_park', 'Parco case mobili', 'Alloggi', 12, 0, '[]', 16),
  ('extended_stay_hotel', 'Residence (soggiorni lunghi)', 'Alloggi', 12, 0, '[]', 17),
  ('resort_hotel', 'Resort', 'Alloggi', 12, 0, '[]', 18),
  ('woods', 'Bosco', 'Natura', 13, 0, '[]', 1),
  ('river', 'Fiume', 'Natura', 13, 0, '[]', 2),
  ('island', 'Isola', 'Natura', 13, 0, '[]', 3),
  ('lake', 'Lago', 'Natura', 13, 0, '[]', 4),
  ('scenic_spot', 'Punto panoramico', 'Natura', 13, 0, '[]', 5),
  ('nature_preserve', 'Riserva naturale', 'Natura', 13, 0, '[]', 6),
  ('beach', 'Spiaggia', 'Natura', 13, 0, '[]', 7),
  ('mountain_peak', 'Vetta', 'Natura', 13, 0, '[]', 8),
  ('church', 'Chiesa', 'Luoghi di culto', 14, 0, '["chiesa"]', 1),
  ('mosque', 'Moschea', 'Luoghi di culto', 14, 0, '[]', 2),
  ('shinto_shrine', 'Santuario shintoista', 'Luoghi di culto', 14, 0, '[]', 3),
  ('synagogue', 'Sinagoga', 'Luoghi di culto', 14, 0, '[]', 4),
  ('buddhist_temple', 'Tempio buddista', 'Luoghi di culto', 14, 0, '[]', 5),
  ('hindu_temple', 'Tempio indù', 'Luoghi di culto', 14, 0, '[]', 6),
  ('service', 'Servizio', 'Servizi', 15, 1, '[]', 1),
  ('insurance_agency', 'Agenzia di assicurazioni', 'Servizi', 15, 0, '["assicurazione"]', 2),
  ('tour_agency', 'Agenzia di tour', 'Servizi', 15, 0, '[]', 3),
  ('travel_agency', 'Agenzia di viaggi', 'Servizi', 15, 0, '["agenzia viaggi"]', 4),
  ('real_estate_agency', 'Agenzia immobiliare', 'Servizi', 15, 0, '["agenzia immobiliare","immobiliare"]', 5),
  ('employment_agency', 'Agenzia per il lavoro', 'Servizi', 15, 0, '[]', 6),
  ('child_care_agency', 'Agenzia per l''infanzia', 'Servizi', 15, 0, '[]', 7),
  ('association_or_organization', 'Associazione o organizzazione', 'Servizi', 15, 0, '[]', 8),
  ('astrologer', 'Astrologo', 'Servizi', 15, 0, '[]', 9),
  ('lawyer', 'Avvocato', 'Servizi', 15, 0, '["avvocato","studio legale"]', 10),
  ('barber_shop', 'Barbiere', 'Servizi', 15, 0, '["barbiere"]', 11),
  ('psychic', 'Cartomante', 'Servizi', 15, 0, '[]', 12),
  ('cemetery', 'Cimitero', 'Servizi', 15, 0, '[]', 13),
  ('food_delivery', 'Consegna di cibo', 'Servizi', 15, 0, '[]', 14),
  ('consultant', 'Consulente', 'Servizi', 15, 0, '[]', 15),
  ('marketing_consultant', 'Consulente di marketing', 'Servizi', 15, 0, '[]', 16),
  ('courier_service', 'Corriere', 'Servizi', 15, 0, '[]', 17),
  ('pet_care', 'Cura degli animali', 'Servizi', 15, 0, '[]', 18),
  ('hair_care', 'Cura dei capelli', 'Servizi', 15, 0, '[]', 19),
  ('electrician', 'Elettricista', 'Servizi', 15, 0, '["impianti elettrici","elettricista"]', 20),
  ('beautician', 'Estetista', 'Servizi', 15, 0, '[]', 21),
  ('locksmith', 'Fabbro', 'Servizi', 15, 0, '["fabbro","serrature"]', 22),
  ('florist', 'Fioraio', 'Servizi', 15, 0, '["fiorista"]', 23),
  ('plumber', 'Idraulico', 'Servizi', 15, 0, '["caldaia","caldaie","idraulico","termoidraulico","riscaldamento"]', 24),
  ('painter', 'Imbianchino', 'Servizi', 15, 0, '["imbianchino","tinteggiatore"]', 25),
  ('roofing_contractor', 'Impresa di coperture', 'Servizi', 15, 0, '["tetti","copertura"]', 26),
  ('laundry', 'Lavanderia', 'Servizi', 15, 0, '["lavanderia","tintoria"]', 27),
  ('aircraft_rental_service', 'Noleggio aerei', 'Servizi', 15, 0, '[]', 28),
  ('funeral_home', 'Onoranze funebri', 'Servizi', 15, 0, '["pompe funebri"]', 29),
  ('telecommunications_service_provider', 'Operatore di telecomunicazioni', 'Servizi', 15, 0, '[]', 30),
  ('summer_camp_organizer', 'Organizzatore di centri estivi', 'Servizi', 15, 0, '[]', 31),
  ('non_profit_organization', 'Organizzazione non profit', 'Servizi', 15, 0, '[]', 32),
  ('hair_salon', 'Parrucchiere', 'Servizi', 15, 0, '["parrucchiere","parrucchiera"]', 33),
  ('pet_boarding_service', 'Pensione per animali', 'Servizi', 15, 0, '[]', 34),
  ('foot_care', 'Podologo', 'Servizi', 15, 0, '[]', 35),
  ('beauty_salon', 'Salone di bellezza', 'Servizi', 15, 0, '[]', 36),
  ('nail_salon', 'Salone di manicure', 'Servizi', 15, 0, '[]', 37),
  ('tailor', 'Sarto', 'Servizi', 15, 0, '[]', 38),
  ('storage', 'Self-storage', 'Servizi', 15, 0, '[]', 39),
  ('chauffeur_service', 'Servizio con autista', 'Servizi', 15, 0, '[]', 40),
  ('catering_service', 'Servizio di catering', 'Servizi', 15, 0, '[]', 41),
  ('shipping_service', 'Servizio di spedizioni', 'Servizi', 15, 0, '[]', 42),
  ('body_art_service', 'Tatuaggi e piercing', 'Servizi', 15, 0, '[]', 43),
  ('moving_company', 'Traslochi', 'Servizi', 15, 0, '["traslochi"]', 44),
  ('makeup_artist', 'Truccatore', 'Servizi', 15, 0, '[]', 45),
  ('tourist_information_center', 'Ufficio informazioni turistiche', 'Servizi', 15, 0, '[]', 46),
  ('veterinary_care', 'Veterinario', 'Servizi', 15, 0, '["veterinario"]', 47),
  ('store', 'Negozio', 'Negozi', 16, 1, '[]', 1),
  ('clothing_store', 'Abbigliamento', 'Negozi', 16, 0, '[]', 2),
  ('womens_clothing_store', 'Abbigliamento donna', 'Negozi', 16, 0, '[]', 3),
  ('sportswear_store', 'Abbigliamento sportivo', 'Negozi', 16, 0, '[]', 4),
  ('grocery_store', 'Alimentari', 'Negozi', 16, 0, '[]', 5),
  ('asian_grocery_store', 'Alimentari asiatici', 'Negozi', 16, 0, '[]', 6),
  ('home_goods_store', 'Articoli per la casa', 'Negozi', 16, 0, '[]', 7),
  ('sporting_goods_store', 'Articoli sportivi', 'Negozi', 16, 0, '[]', 8),
  ('home_improvement_store', 'Bricolage', 'Negozi', 16, 0, '["bricolage","fai da te"]', 9),
  ('warehouse_store', 'Cash and carry', 'Negozi', 16, 0, '[]', 10),
  ('shopping_mall', 'Centro commerciale', 'Negozi', 16, 0, '[]', 11),
  ('discount_store', 'Discount', 'Negozi', 16, 0, '[]', 12),
  ('general_store', 'Emporio', 'Negozi', 16, 0, '[]', 13),
  ('hardware_store', 'Ferramenta', 'Negozi', 16, 0, '["ferramenta"]', 14),
  ('jewelry_store', 'Gioielleria', 'Negozi', 16, 0, '["gioielleria"]', 15),
  ('department_store', 'Grande magazzino', 'Negozi', 16, 0, '[]', 16),
  ('wholesaler', 'Grossista', 'Negozi', 16, 0, '[]', 17),
  ('hypermarket', 'Ipermercato', 'Negozi', 16, 0, '[]', 18),
  ('book_store', 'Libreria', 'Negozi', 16, 0, '[]', 19),
  ('butcher_shop', 'Macelleria', 'Negozi', 16, 0, '["macelleria"]', 20),
  ('building_materials_store', 'Materiali edili', 'Negozi', 16, 0, '["edilizia","materiali edili"]', 21),
  ('flea_market', 'Mercatino delle pulci', 'Negozi', 16, 0, '[]', 22),
  ('market', 'Mercato', 'Negozi', 16, 0, '[]', 23),
  ('farmers_market', 'Mercato contadino', 'Negozi', 16, 0, '[]', 24),
  ('convenience_store', 'Minimarket', 'Negozi', 16, 0, '[]', 25),
  ('food_store', 'Negozio alimentare', 'Negozi', 16, 0, '[]', 26),
  ('thrift_store', 'Negozio dell''usato', 'Negozi', 16, 0, '[]', 27),
  ('pet_store', 'Negozio di animali', 'Negozi', 16, 0, '[]', 28),
  ('gift_shop', 'Negozio di articoli da regalo', 'Negozi', 16, 0, '[]', 29),
  ('bicycle_store', 'Negozio di biciclette', 'Negozi', 16, 0, '[]', 30),
  ('electronics_store', 'Negozio di elettronica', 'Negozi', 16, 0, '[]', 31),
  ('toy_store', 'Negozio di giocattoli', 'Negozi', 16, 0, '[]', 32),
  ('liquor_store', 'Negozio di liquori', 'Negozi', 16, 0, '[]', 33),
  ('furniture_store', 'Negozio di mobili', 'Negozi', 16, 0, '["mobili"]', 34),
  ('health_food_store', 'Negozio di prodotti biologici e dietetici', 'Negozi', 16, 0, '[]', 35),
  ('shoe_store', 'Negozio di scarpe', 'Negozi', 16, 0, '[]', 36),
  ('tea_store', 'Negozio di tè', 'Negozi', 16, 0, '[]', 37),
  ('cell_phone_store', 'Negozio di telefonia', 'Negozi', 16, 0, '[]', 38),
  ('cosmetics_store', 'Profumeria', 'Negozi', 16, 0, '[]', 39),
  ('auto_parts_store', 'Ricambi auto', 'Negozi', 16, 0, '[]', 40),
  ('supermarket', 'Supermercato', 'Negozi', 16, 0, '["alimentari"]', 41),
  ('discount_supermarket', 'Supermercato discount', 'Negozi', 16, 0, '[]', 42),
  ('garden_center', 'Vivaio/garden center', 'Negozi', 16, 0, '["vivaio"]', 43),
  ('sports_activity_location', 'Impianto per attività sportive', 'Sport', 17, 1, '[]', 1),
  ('sports_coaching', 'Allenatore sportivo', 'Sport', 17, 0, '[]', 2),
  ('arena', 'Arena', 'Sport', 17, 0, '[]', 3),
  ('golf_course', 'Campo da golf', 'Sport', 17, 0, '[]', 4),
  ('tennis_court', 'Campo da tennis', 'Sport', 17, 0, '[]', 5),
  ('athletic_field', 'Campo sportivo', 'Sport', 17, 0, '[]', 6),
  ('fitness_center', 'Centro fitness', 'Sport', 17, 0, '[]', 7),
  ('sports_club', 'Club sportivo', 'Sport', 17, 0, '[]', 8),
  ('sports_complex', 'Complesso sportivo', 'Sport', 17, 0, '[]', 9),
  ('indoor_golf_course', 'Golf indoor', 'Sport', 17, 0, '[]', 10),
  ('race_course', 'Ippodromo/pista', 'Sport', 17, 0, '[]', 11),
  ('fishing_pond', 'Laghetto di pesca', 'Sport', 17, 0, '[]', 12),
  ('fishing_pier', 'Molo di pesca', 'Sport', 17, 0, '[]', 13),
  ('gym', 'Palestra', 'Sport', 17, 0, '["palestra"]', 14),
  ('playground', 'Parco giochi', 'Sport', 17, 0, '[]', 15),
  ('fishing_charter', 'Pesca charter', 'Sport', 17, 0, '[]', 16),
  ('swimming_pool', 'Piscina', 'Sport', 17, 0, '[]', 17),
  ('ice_skating_rink', 'Pista di pattinaggio', 'Sport', 17, 0, '[]', 18),
  ('sports_school', 'Scuola sportiva', 'Sport', 17, 0, '[]', 19),
  ('stadium', 'Stadio', 'Sport', 17, 0, '[]', 20),
  ('ski_resort', 'Stazione sciistica', 'Sport', 17, 0, '[]', 21),
  ('transportation_service', 'Servizio di trasporto', 'Trasporti', 18, 1, '[]', 1),
  ('airport', 'Aeroporto', 'Trasporti', 18, 0, '[]', 2),
  ('international_airport', 'Aeroporto internazionale', 'Trasporti', 18, 0, '[]', 3),
  ('truck_stop', 'Area di servizio per camion', 'Trasporti', 18, 0, '[]', 4),
  ('train_ticket_office', 'Biglietteria ferroviaria', 'Trasporti', 18, 0, '[]', 5),
  ('toll_station', 'Casello', 'Trasporti', 18, 0, '[]', 6),
  ('transit_depot', 'Deposito mezzi pubblici', 'Trasporti', 18, 0, '[]', 7),
  ('heliport', 'Eliporto', 'Trasporti', 18, 0, '[]', 8),
  ('tram_stop', 'Fermata del tram', 'Trasporti', 18, 0, '[]', 9),
  ('transit_stop', 'Fermata del trasporto pubblico', 'Trasporti', 18, 0, '[]', 10),
  ('bus_stop', 'Fermata dell''autobus', 'Trasporti', 18, 0, '[]', 11),
  ('park_and_ride', 'Parcheggio di interscambio', 'Trasporti', 18, 0, '[]', 12),
  ('airstrip', 'Pista di atterraggio', 'Trasporti', 18, 0, '[]', 13),
  ('bridge', 'Ponte', 'Trasporti', 18, 0, '[]', 14),
  ('taxi_stand', 'Posteggio taxi', 'Trasporti', 18, 0, '[]', 15),
  ('ferry_service', 'Servizio di traghetti', 'Trasporti', 18, 0, '[]', 16),
  ('taxi_service', 'Servizio taxi', 'Trasporti', 18, 0, '[]', 17),
  ('bus_station', 'Stazione degli autobus', 'Trasporti', 18, 0, '[]', 18),
  ('subway_station', 'Stazione della metropolitana', 'Trasporti', 18, 0, '[]', 19),
  ('light_rail_station', 'Stazione della metropolitana leggera', 'Trasporti', 18, 0, '[]', 20),
  ('bike_sharing_station', 'Stazione di bike sharing', 'Trasporti', 18, 0, '[]', 21),
  ('transit_station', 'Stazione di transito', 'Trasporti', 18, 0, '[]', 22),
  ('train_station', 'Stazione ferroviaria', 'Trasporti', 18, 0, '[]', 23),
  ('ferry_terminal', 'Terminal dei traghetti', 'Trasporti', 18, 0, '[]', 24);
